server:
  port: 8085

spring:
  application:
    name: CONFIGSERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhishektripathi66/microservice-configurations/
          clone-on-start: true